POST http://localhost:5000/api/auth/register HTTP/1.1
Content-type: application/json

{
    "username": "kohei",
    "password": "123",
    "role": 1
}

### LOGIN
POST https://vz-manga.onrender.com/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "dinhvan3111",
    "password": "123"
}

### REFRESH TOKEN
POST http://localhost:5000/api/auth/refresh HTTP/1.1
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTE0M2UyYzAxMDQ0NzcxYjUzYzciLCJyb2xlIjoyLCJpYXQiOjE2OTc1NTc0MDYsImV4cCI6MTY5NzczMDIwNn0.-DjZNhzikPzk0sgX7YssrXxBa5BKVNXkQ3bLtnD5lNs"
}

### ADD MANGA
POST http://localhost:5000/api/manga HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5ODM4NDQ0MDcwZGVmMGRkZmQyOGQiLCJpYXQiOjE2OTYxNzY5NTd9.0Kk7-jwh-bFYyI2K9xeu-fkECKbB8LQS0jk5nYcpe9U

{
    "name": "Boku",
    "description": "My Hero Academia is a Japanese superhero manga series written and illustrated by Kōhei Horikoshi. It has been serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump since July 2014, with its chapters additionally collected into 38 tankōbon volumes as of June 2023.",
    "thumbUrl": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Boku_no_Hero_Academia_Volume_1.png/220px-Boku_no_Hero_Academia_Volume_1.png",
    "authors": ["Kohei Horikoshi"],
    "artists": ["Kohei Horikoshi"],
    "transTeam": "Vz3",
    "genres": ["652291e173f058e83b54480d", "652291f673f058e83b54480f", "652291fa73f058e83b544811"],
    "status": 3
}

###
GET http://localhost:5000/api/manga?page=1&limit=5 HTTP/1.1
# Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5ODM4NDQ0MDcwZGVmMGRkZmQyOGQiLCJpYXQiOjE2OTYxNzY5NTd9.0Kk7-jwh-bFYyI2K9xeu-fkECKbB8LQS0jk5nYcpe9U

# {
#     "name": "Jujutsu Kaisen",
#     "description": "Jujutsu Kaisen is a Japanese manga series written and illustrated by Gege Akutami. It has been serialized in Shueisha's shōnen manga magazine Weekly Shōnen Jump since March 2018, with its chapters collected and published in 23 tankōbon volumes as of July 2023",
#     "thumbUrl": "https://m.media-amazon.com/images/M/MV5BMTMwMDM4N2EtOTJiYy00OTQ0LThlZDYtYWUwOWFlY2IxZGVjXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg"
    
# }

### GET MANGA DETAIL
GET http://localhost:5000/api/manga/651a9ef6d9e7cb19c17fcd4e HTTP/1.1 

### UPDATE MANGA
PUT http://localhost:5000/api/manga/652d3bd66a84f95538d73d18 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTExNmUyYzAxMDQ0NzcxYjUzYzQiLCJyb2xlIjowLCJpYXQiOjE2OTYyNDA3NDR9.qlgwo8FUChaZKEknLGq7zDYAqmqlgOxGY83b2jcX1Bk

{
    "description": "One rainy night, Saki is rushing to a piano lesson when she crashes into a beautiful, long-haired girl, dropping her sheet music in the process. Saki stutters an apology, but the girl simply hands back her sheet music and leaves without a word. Saki begins her first day of high school the following morning, only to find the stranger from the night before sitting at the desk next to hers. She learns that the girl’s name is Kanon and that she is not quite completely deaf, but very hard of hearing. Though Kanon needs to be close to people to read their lips, she tends to push people away with her icy demeanor. Through one kind gesture, Saki slowly begins breaking down the walls around Kanon, even as she feels something new blossoming within her. [Kodansha]"
}

### DELETE MANGA

DELETE http://localhost:5000/api/manga/651a9ef6d9e7cb19c17fcd4e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTExNmUyYzAxMDQ0NzcxYjUzYzQiLCJyb2xlIjowLCJpYXQiOjE2OTYyNDA3NDR9.qlgwo8FUChaZKEknLGq7zDYAqmqlgOxGY83b2jcX1Bk

### SEARCH MANGA
GET http://localhost:5000/api/manga/search?key=&page=1&limit=2 HTTP/1.1


### =========================================GENRE========================================
POST http://localhost:5000/api/genre HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTExNmUyYzAxMDQ0NzcxYjUzYzQiLCJyb2xlIjowLCJpYXQiOjE2OTYyNDA3NDR9.qlgwo8FUChaZKEknLGq7zDYAqmqlgOxGY83b2jcX1Bk

{
    "name": "Fantasy"
}

### GET ALL GENRES
GET http://localhost:5000/api/genre HTTP/1.1

### =========================================CHAPTER========================================


### ADD CHAPTER
POST http://localhost:5000/api/chapter HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTExNmUyYzAxMDQ0NzcxYjUzYzQiLCJyb2xlIjowLCJpYXQiOjE2OTYyNDA3NDR9.qlgwo8FUChaZKEknLGq7zDYAqmqlgOxGY83b2jcX1Bk

{
    "mangaId": "6522aec57a2b944f322a6161",
    "title": "Chapter 1: Midoriya Izuku The Origin"
}

### UPDATE CHAPTER
PUT http://localhost:5000/api/chapter/652a1346ce2f46da79476126 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTExNmUyYzAxMDQ0NzcxYjUzYzQiLCJyb2xlIjowLCJpYXQiOjE2OTYyNDA3NDR9.qlgwo8FUChaZKEknLGq7zDYAqmqlgOxGY83b2jcX1Bk

{
    "mangaId": "6522aec57a2b944f322a6161",
    "title": "Chapter 1: Midoriya Izuku The Origin",
    "listImgUrl": []
}

### GET ALL CHAPTER
GET http://localhost:5000/api/chapter/651a9ef6d9e7cb19c17fcd4e?page=1&limit=10 HTTP/1.1

### GET ALL IMAGES OF CHAPTER

GET http://localhost:5000/api/chapter/652a1346ce2f46da79476126/imgs HTTP/1.1


### =========================================FAVOURITE========================================

### ADD MANGA TO FAV
POST http://localhost:5000/api/favourite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTE0M2UyYzAxMDQ0NzcxYjUzYzciLCJyb2xlIjoyLCJpYXQiOjE2OTc1MTUzNjIsImV4cCI6MTY5NzYwMTc2Mn0.X8iZXfv5tDIjEkXW92VSJtkY9l5mBsK99CbdbpXi-7M

{
    "mangaId": "652d3aa36a84f95538d73cf1"
}

### GET LIST FAV
GET http://localhost:5000/api/favourite?page=1&limit=10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTE0M2UyYzAxMDQ0NzcxYjUzYzciLCJyb2xlIjoyLCJpYXQiOjE3MjY1MDE5MzksImV4cCI6MTcyNjUwMjgzOX0.uPm7KDuOcxglrBiYVcYzHYVR48LtTCT_IuqT6QxXASY

### REMOVE MANGA FROM FAV
DELETE http://localhost:5000/api/favourite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhOTE0M2UyYzAxMDQ0NzcxYjUzYzciLCJyb2xlIjoyLCJpYXQiOjE2OTc1MTUzNjIsImV4cCI6MTY5NzYwMTc2Mn0.X8iZXfv5tDIjEkXW92VSJtkY9l5mBsK99CbdbpXi-7M

{
    "mangaId": "652d3aa36a84f95538d73cf1"
}